import PolicyTemplate from "./PolicyTemplate";

const PrivacyPolicyView = () => {
  return (
    <PolicyTemplate>
      <PrivacyPolicyContent />
    </PolicyTemplate>
  );
};

const PrivacyPolicyContent = () => {
  return (
    <div>
      <h1>Privacy Policy</h1>
      <p>
        <strong>Last updated:</strong> March 05, 2024
      </p>

      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>

      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Free Privacy Policy Generator.
      </p>

      <h2>Interpretation and Definitions</h2>

      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3>Definitions</h3>

      <p>
        <strong>Account</strong> means a unique account created for You to
        access our Service or parts of our Service.
      </p>

      <p>
        <strong>Affiliate</strong> means an entity that controls, is controlled
        by or is under common control with a party, where &quot;control&quot;
        means ownership of 50% or more of the shares, equity interest or other
        securities entitled to vote for election of directors or other managing
        authority.
      </p>

      <p>
        <strong>Company</strong> (referred to as either &quot;the Company&quot;,
        &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
        refers to Speed Reader.
      </p>

      <p>
        <strong>Cookies</strong> are small files that are placed on Your
        computer, mobile device or any other device by a website, containing the
        details of Your browsing history on that website among its many uses.
      </p>

      <p>
        <strong>Country</strong> refers to: United Kingdom
      </p>

      <p>
        <strong>Device</strong> means any device that can access the Service
        such as a computer, a cellphone or a digital tablet.
      </p>

      <p>
        <strong>Personal Data</strong> is any information that relates to an
        identified or identifiable individual.
      </p>

      <p>
        <strong>Service</strong> refers to the Website.
      </p>

      <p>
        <strong>Service Provider</strong> means any natural or legal person who
        processes the data on behalf of the Company. It refers to third-party
        companies or individuals employed by the Company to facilitate the
        Service, to provide the Service on behalf of the Company, to perform
        services related to the Service or to assist the Company in analyzing
        how the Service is used.
      </p>

      <p>
        <strong>Usage Data</strong> refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
      </p>

      <p>
        <strong>Website</strong> refers to Speed Reader, accessible from{" "}
        <a href="https://speed-reader.doc.ic.ac.uk" style={{ color: "white" }}>
          https://speed-reader.doc.ic.ac.uk
        </a>
      </p>

      <p>
        <strong>You</strong> means the individual accessing or using the
        Service, or the company, or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.
      </p>

      <h2>Collecting and Using Your Personal Data</h2>

      <h3>Data Storage Disclaimer</h3>

      <p>
        We do not store any images after the game ends. Any images used during
        gameplay, including those captured by WebGazer&#39;s eye tracking
        technology in Adaptive Mode, are processed temporarily and locally on
        the user&#39;s device for the purpose of providing real-time feedback
        and improving the user experience. This temporary data is stored
        client-side and is not saved or transmitted to our servers. It is
        automatically cleared once the session ends.
      </p>
      <p>
        Please be aware that although the camera may appear operational
        following the initial calibration, we solely utilize camera data during
        the game itself.
      </p>

      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>

      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>

      <ul>
        <li>Email address</li>
        <li>Username</li>
      </ul>

      <h4>Tracking Technologies and Cookies</h4>

      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>

      <ul>
        <li>
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons:</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>

      <p>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser. Learn more about cookies on the Free Privacy
        Policy website article.
      </p>

      <p>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>

      <ul>
        <li>
          <strong>Necessary / Essential Cookies</strong>
        </li>
        <ul>
          <li>
            <strong>Type:</strong> Session Cookies
          </li>
          <li>
            <strong>Administered by:</strong> Us
          </li>
          <li>
            <strong>Purpose:</strong> These Cookies are essential to provide You
            with services available through the Website and to enable You to use
            some of its features. They help to authenticate users and prevent
            fraudulent use of user accounts. Without these Cookies, the services
            that You have asked for cannot be provided, and We only use these
            Cookies to provide You with those services.
          </li>
        </ul>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
        </li>
        <ul>
          <li>
            <strong>Type:</strong> Persistent Cookies
          </li>
          <li>
            <strong>Administered by:</strong> Us
          </li>
          <li>
            <strong>Purpose:</strong> These Cookies identify if users have
            accepted the use of cookies on the Website.
          </li>
        </ul>
        <li>
          <strong>Functionality Cookies</strong>
        </li>
        <ul>
          <li>
            <strong>Type:</strong> Persistent Cookies
          </li>
          <li>
            <strong>Administered by:</strong> Us
          </li>
          <li>
            <strong>Purpose:</strong> These Cookies allow us to remember choices
            You make when You use the Website, such as remembering your login
            details or language preference. The purpose of these Cookies is to
            provide You with a more personal experience and to avoid You having
            to re-enter your preferences every time You use the Website.
          </li>
        </ul>
      </ul>

      <h3>Links to Other Websites</h3>

      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&#39;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </p>

      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>

      <h3>Changes to this Privacy Policy</h3>

      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>

      <p>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </p>

      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      <h3>Contact Us</h3>

      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>

      <p>By email: speed.reader24@gmail.com</p>
    </div>
  );
};

export default PrivacyPolicyView;
