FROM node:21

WORKDIR /app

# Install Java for openapi-generator.
RUN apt update -y && \
    apt install -y openjdk-17-jre

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

EXPOSE 8080
CMD PORT=8080 HOST=0.0.0.0 yarn start
