services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      # Cannot use ports below 1000 (e.g. 80) 
      # as they are previleged ports that require root access.
      - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/default
      - POSTGRES_TEST_URL=postgresql://postgres:postgres@postgres-test:5432/default
      - MONGO_URL=mongodb://mongo:27017/default
      - MONGO_TEST_URL=mongodb://mongo-test:27017/default
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/migrations:/app/migrations
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - postgres-test
      - mongo
      - mongo-test
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  postgres-test:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-test-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=default
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  mongo-test:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=default
    volumes:
      - mongodb-test-data:/data/db
    ports:
      - 27018:27017
volumes:
  postgresql-data:
  postgresql-test-data:
  mongodb-data:
  mongodb-test-data:
