services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - node_modules:/app/node_modules
    ports:
      # Cannot use ports below 1000 (e.g. 80) 
      # as they are previleged ports that require root access.
      - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/default
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  node_modules:
  postgresql-data:
