FROM python:3.12

WORKDIR /app

COPY poetry.lock pyproject.toml ./
RUN pip install poetry==1.5.1 && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-dev

COPY . .
# Install root and dev dependencies to setup CLI.
RUN poetry install

EXPOSE 8000
CMD uvicorn src.main:app --reload --port 8000 --host 0.0.0.0
