FROM python:3.12

WORKDIR /app

COPY poetry.lock pyproject.toml ./
RUN pip install poetry==1.5.1 && \
    poetry config virtualenvs.create false && \
    poetry install

COPY . .

EXPOSE 8000
CMD uvicorn src.main:app --reload --port 8000 --host 0.0.0.0
