/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BodyGetUserAvailableTexts
 */
export interface BodyGetUserAvailableTexts {
    /**
     * 
     * @type {BodyGetUserAvailableTextsTextFilter}
     * @memberof BodyGetUserAvailableTexts
     */
    textFilter?: BodyGetUserAvailableTextsTextFilter;
    /**
     * 
     * @type {BodyGetUserAvailableTextsTextSort}
     * @memberof BodyGetUserAvailableTexts
     */
    textSort?: BodyGetUserAvailableTextsTextSort;
}
/**
 * 
 * @export
 * @interface BodyGetUserAvailableTextsTextFilter
 */
export interface BodyGetUserAvailableTextsTextFilter {
    /**
     * 
     * @type {GameMode}
     * @memberof BodyGetUserAvailableTextsTextFilter
     */
    gameMode?: GameMode;
    /**
     * 
     * @type {Difficulty}
     * @memberof BodyGetUserAvailableTextsTextFilter
     */
    difficulty?: Difficulty;
}
/**
 * 
 * @export
 * @interface BodyGetUserAvailableTextsTextSort
 */
export interface BodyGetUserAvailableTextsTextSort {
    /**
     * 
     * @type {any}
     * @memberof BodyGetUserAvailableTextsTextSort
     */
    field: any;
    /**
     * 
     * @type {any}
     * @memberof BodyGetUserAvailableTextsTextSort
     */
    ascending?: any;
}
/**
 * 
 * @export
 * @interface BodyPostAnswers
 */
export interface BodyPostAnswers {
    /**
     * 
     * @type {Array<QuestionAnswer>}
     * @memberof BodyPostAnswers
     */
    answers: Array<QuestionAnswer>;
    /**
     * 
     * @type {number}
     * @memberof BodyPostAnswers
     */
    averageWpm: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof BodyPostAnswers
     */
    intervalWpms: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof BodyPostAnswers
     */
    gameMode: string;
    /**
     * 
     * @type {GameSubmode}
     * @memberof BodyPostAnswers
     */
    gameSubmode?: GameSubmode;
}
/**
 * 
 * @export
 * @interface ClientId
 */
export interface ClientId {
}
/**
 * 
 * @export
 * @interface ClientSecret
 */
export interface ClientSecret {
}
/**
 * 
 * @export
 * @interface Difficulty
 */
export interface Difficulty {
}
/**
 * 
 * @export
 * @interface GameMode
 */
export interface GameMode {
}
/**
 * 
 * @export
 * @interface GameSubmode
 */
export interface GameSubmode {
}
/**
 * 
 * @export
 * @interface GrantType
 */
export interface GrantType {
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface History
 */
export interface History {
    /**
     * 
     * @type {string}
     * @memberof History
     */
    textId: string;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    gameMode: string;
    /**
     * 
     * @type {GameSubmode}
     * @memberof History
     */
    gameSubmode: GameSubmode;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    averageWpm: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof History
     */
    intervalWpms: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    score: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof History
     */
    answers: Array<number>;
}
/**
 * 
 * @export
 * @interface Question
 */
export interface Question {
    /**
     * 
     * @type {string}
     * @memberof Question
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Question
     */
    content: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Question
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Question
     */
    correctOption: number;
}
/**
 * 
 * @export
 * @interface QuestionAnswer
 */
export interface QuestionAnswer {
    /**
     * 
     * @type {string}
     * @memberof QuestionAnswer
     */
    questionId: string;
    /**
     * 
     * @type {number}
     * @memberof QuestionAnswer
     */
    selectedOption: number;
}
/**
 * 
 * @export
 * @interface QuestionResult
 */
export interface QuestionResult {
    /**
     * 
     * @type {string}
     * @memberof QuestionResult
     */
    questionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof QuestionResult
     */
    correct: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuestionResult
     */
    selectedOption: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionResult
     */
    correctOption: number;
}
/**
 * 
 * @export
 * @interface Text
 */
export interface Text {
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    difficulty: string;
    /**
     * 
     * @type {number}
     * @memberof Text
     */
    wordCount: number;
}
/**
 * 
 * @export
 * @interface TextFilter
 */
export interface TextFilter {
    /**
     * 
     * @type {GameMode}
     * @memberof TextFilter
     */
    gameMode?: GameMode;
    /**
     * 
     * @type {Difficulty}
     * @memberof TextFilter
     */
    difficulty?: Difficulty;
}
/**
 * 
 * @export
 * @interface TextSort
 */
export interface TextSort {
    /**
     * 
     * @type {string}
     * @memberof TextSort
     */
    field: string;
    /**
     * 
     * @type {boolean}
     * @memberof TextSort
     */
    ascending?: boolean;
}
/**
 * 
 * @export
 * @interface UserAvailableTexts
 */
export interface UserAvailableTexts {
    /**
     * 
     * @type {Array<Text>}
     * @memberof UserAvailableTexts
     */
    texts: Array<Text>;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    totalTexts: number;
}
/**
 * 
 * @export
 * @interface UserStatistics
 */
export interface UserStatistics {
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    minWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    maxWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    averageWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    averageScore: number;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    loc: Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    type: string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuiz: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/quiz`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Admin Dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminDashboard: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuiz(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createQuiz(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.createQuiz']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Admin Dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdminDashboard(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminDashboard(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getAdminDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuiz(options?: any): AxiosPromise<any> {
            return localVarFp.createQuiz(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Admin Dashboard
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminDashboard(options?: any): AxiosPromise<any> {
            return localVarFp.getAdminDashboard(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @summary Create Quiz
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public createQuiz(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).createQuiz(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Admin Dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getAdminDashboard(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getAdminDashboard(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authenticate User
         * @param {string} username 
         * @param {string} password 
         * @param {GrantType} [grantType] 
         * @param {string} [scope] 
         * @param {ClientId} [clientId] 
         * @param {ClientSecret} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateUser: async (username: string, password: string, grantType?: GrantType, scope?: string, clientId?: ClientId, clientSecret?: ClientSecret, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('authenticateUser', 'username', username)
            // verify required parameter 'password' is not null or undefined
            assertParamExists('authenticateUser', 'password', password)
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (grantType !== undefined) { 
                localVarFormParams.set('grant_type', grantType as any);
            }
    
            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }
    
            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }
    
            if (scope !== undefined) { 
                localVarFormParams.set('scope', scope as any);
            }
    
            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }
    
            if (clientSecret !== undefined) { 
                localVarFormParams.set('client_secret', clientSecret as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh Access Token
         * @param {any} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshAccessToken: async (refreshToken: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshToken' is not null or undefined
            assertParamExists('refreshAccessToken', 'refreshToken', refreshToken)
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (refreshToken != null) {
                localVarHeaderParameter['refresh-token'] = typeof refreshToken === 'string'
                    ? refreshToken
                    : JSON.stringify(refreshToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Authenticate User
         * @param {string} username 
         * @param {string} password 
         * @param {GrantType} [grantType] 
         * @param {string} [scope] 
         * @param {ClientId} [clientId] 
         * @param {ClientSecret} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticateUser(username: string, password: string, grantType?: GrantType, scope?: string, clientId?: ClientId, clientSecret?: ClientSecret, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticateUser(username, password, grantType, scope, clientId, clientSecret, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authenticateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh Access Token
         * @param {any} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshAccessToken(refreshToken: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshAccessToken(refreshToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.refreshAccessToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Authenticate User
         * @param {string} username 
         * @param {string} password 
         * @param {GrantType} [grantType] 
         * @param {string} [scope] 
         * @param {ClientId} [clientId] 
         * @param {ClientSecret} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticateUser(username: string, password: string, grantType?: GrantType, scope?: string, clientId?: ClientId, clientSecret?: ClientSecret, options?: any): AxiosPromise<any> {
            return localVarFp.authenticateUser(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh Access Token
         * @param {any} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshAccessToken(refreshToken: any, options?: any): AxiosPromise<any> {
            return localVarFp.refreshAccessToken(refreshToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Authenticate User
     * @param {string} username 
     * @param {string} password 
     * @param {GrantType} [grantType] 
     * @param {string} [scope] 
     * @param {ClientId} [clientId] 
     * @param {ClientSecret} [clientSecret] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authenticateUser(username: string, password: string, grantType?: GrantType, scope?: string, clientId?: ClientId, clientSecret?: ClientSecret, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authenticateUser(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh Access Token
     * @param {any} refreshToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public refreshAccessToken(refreshToken: any, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).refreshAccessToken(refreshToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GameApi - axios parameter creator
 * @export
 */
export const GameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextQuestions: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getNextQuestions', 'textId', textId)
            const localVarPath = `/game/texts/{text_id}/questions/next`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextText: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/game/texts/next`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getText', 'textId', textId)
            const localVarPath = `/game/texts/{text_id}`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnswers: async (textId: string, bodyPostAnswers: BodyPostAnswers, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('postAnswers', 'textId', textId)
            // verify required parameter 'bodyPostAnswers' is not null or undefined
            assertParamExists('postAnswers', 'bodyPostAnswers', bodyPostAnswers)
            const localVarPath = `/game/texts/{text_id}/answers`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bodyPostAnswers, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GameApi - functional programming interface
 * @export
 */
export const GameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GameApiAxiosParamCreator(configuration)
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextQuestions(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Question>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextQuestions(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.getNextQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextText(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Text>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextText(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.getNextText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getText(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Text>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getText(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.getText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QuestionResult>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postAnswers(textId, bodyPostAnswers, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.postAnswers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GameApi - factory interface
 * @export
 */
export const GameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GameApiFp(configuration)
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextQuestions(textId: string, options?: any): AxiosPromise<Array<Question>> {
            return localVarFp.getNextQuestions(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextText(options?: any): AxiosPromise<Text> {
            return localVarFp.getNextText(options).then((request) => request(axios, basePath));
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText(textId: string, options?: any): AxiosPromise<Text> {
            return localVarFp.getText(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: any): AxiosPromise<Array<QuestionResult>> {
            return localVarFp.postAnswers(textId, bodyPostAnswers, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GameApi - object-oriented interface
 * @export
 * @class GameApi
 * @extends {BaseAPI}
 */
export class GameApi extends BaseAPI {
    /**
     * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
     * @summary Get Next Questions
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public getNextQuestions(textId: string, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).getNextQuestions(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
     * @summary Get Next Text
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public getNextText(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).getNextText(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a text by the given id.
     * @summary Get Text
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public getText(textId: string, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).getText(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Accepts the question answers and other statistics. Returns the results to the answers.
     * @summary Post Answers
     * @param {string} textId 
     * @param {BodyPostAnswers} bodyPostAnswers 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).postAnswers(textId, bodyPostAnswers, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistory: async (historyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'historyId' is not null or undefined
            assertParamExists('getHistory', 'historyId', historyId)
            const localVarPath = `/users/current/results/{history_id}`
                .replace(`{${"history_id"}}`, encodeURIComponent(String(historyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAvailableTexts: async (page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/available_texts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bodyGetUserAvailableTexts, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<History>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getHistories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistory(historyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<History>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistory(historyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserAvailableTexts>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserAvailableTexts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserStatistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserStatistics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistories(options?: any): AxiosPromise<Array<History>> {
            return localVarFp.getHistories(options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistory(historyId: string, options?: any): AxiosPromise<History> {
            return localVarFp.getHistory(historyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: any): AxiosPromise<UserAvailableTexts> {
            return localVarFp.getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics(options?: any): AxiosPromise<UserStatistics> {
            return localVarFp.getUserStatistics(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Gets the history of games played by the user.
     * @summary Get Histories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getHistories(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getHistories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the history of games played by the user.
     * @summary Get History
     * @param {string} historyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getHistory(historyId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getHistory(historyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
     * @summary Get User Available Texts
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the statistics based on the user\'s game history.
     * @summary Get User Statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserStatistics(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserStatistics(options).then((request) => request(this.axios, this.basePath));
    }
}



