/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AdminStatistics
 */
export interface AdminStatistics {
    /**
     * 
     * @type {number}
     * @memberof AdminStatistics
     */
    averageScore: number;
    /**
     * 
     * @type {number}
     * @memberof AdminStatistics
     */
    averageWpm: number;
    /**
     * 
     * @type {number}
     * @memberof AdminStatistics
     */
    minWpm: number;
    /**
     * 
     * @type {number}
     * @memberof AdminStatistics
     */
    maxWpm: number;
}
/**
 * 
 * @export
 * @interface Answer
 */
export interface Answer {
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    questionId: string;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    selectedOption: number;
}
/**
 * 
 * @export
 * @interface BodyGetUserAvailableTexts
 */
export interface BodyGetUserAvailableTexts {
    /**
     * 
     * @type {BodyGetUserAvailableTextsTextFilter}
     * @memberof BodyGetUserAvailableTexts
     */
    textFilter?: BodyGetUserAvailableTextsTextFilter;
    /**
     * 
     * @type {BodyGetUserAvailableTextsTextSort}
     * @memberof BodyGetUserAvailableTexts
     */
    textSort?: BodyGetUserAvailableTextsTextSort;
}
/**
 * 
 * @export
 * @interface BodyGetUserAvailableTextsTextFilter
 */
export interface BodyGetUserAvailableTextsTextFilter {
    /**
     * 
     * @type {GameMode}
     * @memberof BodyGetUserAvailableTextsTextFilter
     */
    gameMode?: GameMode;
    /**
     * 
     * @type {Difficulty}
     * @memberof BodyGetUserAvailableTextsTextFilter
     */
    difficulty?: Difficulty;
}
/**
 * 
 * @export
 * @interface BodyGetUserAvailableTextsTextSort
 */
export interface BodyGetUserAvailableTextsTextSort {
    /**
     * 
     * @type {any}
     * @memberof BodyGetUserAvailableTextsTextSort
     */
    field: any;
    /**
     * 
     * @type {any}
     * @memberof BodyGetUserAvailableTextsTextSort
     */
    ascending?: any;
}
/**
 * 
 * @export
 * @interface BodyPostAnswers
 */
export interface BodyPostAnswers {
    /**
     * 
     * @type {Array<Answer>}
     * @memberof BodyPostAnswers
     */
    answers: Array<Answer>;
    /**
     * 
     * @type {number}
     * @memberof BodyPostAnswers
     */
    averageWpm: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof BodyPostAnswers
     */
    intervalWpms: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof BodyPostAnswers
     */
    gameMode: string;
    /**
     * 
     * @type {string}
     * @memberof BodyPostAnswers
     */
    gameSubmode: string;
    /**
     * 
     * @type {boolean}
     * @memberof BodyPostAnswers
     */
    summary: boolean;
}
/**
 * 
 * @export
 * @interface Difficulty
 */
export interface Difficulty {
}
/**
 * 
 * @export
 * @interface GameMode
 */
export interface GameMode {
}
/**
 * 
 * @export
 * @interface GameSubmode
 */
export interface GameSubmode {
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface History
 */
export interface History {
    /**
     * 
     * @type {string}
     * @memberof History
     */
    textId: string;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    gameMode: string;
    /**
     * 
     * @type {GameSubmode}
     * @memberof History
     */
    gameSubmode: GameSubmode;
    /**
     * 
     * @type {boolean}
     * @memberof History
     */
    summary: boolean;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    averageWpm: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof History
     */
    intervalWpms: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    score: number;
    /**
     * 
     * @type {Array<Result>}
     * @memberof History
     */
    results: Array<Result>;
}
/**
 * 
 * @export
 * @interface Question
 */
export interface Question {
    /**
     * 
     * @type {string}
     * @memberof Question
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Question
     */
    content: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Question
     */
    options: Array<string>;
}
/**
 * 
 * @export
 * @interface QuestionStatistics
 */
export interface QuestionStatistics {
    /**
     * 
     * @type {string}
     * @memberof QuestionStatistics
     */
    questionId: string;
    /**
     * 
     * @type {number}
     * @memberof QuestionStatistics
     */
    averageScore: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof QuestionStatistics
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof QuestionStatistics
     */
    correctOption: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof QuestionStatistics
     */
    selectedOptions: Array<number>;
}
/**
 * 
 * @export
 * @interface QuestionWithCorrectOption
 */
export interface QuestionWithCorrectOption {
    /**
     * 
     * @type {string}
     * @memberof QuestionWithCorrectOption
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionWithCorrectOption
     */
    content: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QuestionWithCorrectOption
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof QuestionWithCorrectOption
     */
    correctOption: number;
}
/**
 * 
 * @export
 * @interface Result
 */
export interface Result {
    /**
     * 
     * @type {string}
     * @memberof Result
     */
    questionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Result
     */
    correct: boolean;
    /**
     * 
     * @type {number}
     * @memberof Result
     */
    correctOption: number;
    /**
     * 
     * @type {number}
     * @memberof Result
     */
    selectedOption: number;
}
/**
 * 
 * @export
 * @interface Text
 */
export interface Text {
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Text
     */
    difficulty: string;
    /**
     * 
     * @type {number}
     * @memberof Text
     */
    wordCount: number;
}
/**
 * 
 * @export
 * @interface TextFilter
 */
export interface TextFilter {
    /**
     * 
     * @type {GameMode}
     * @memberof TextFilter
     */
    gameMode?: GameMode;
    /**
     * 
     * @type {Difficulty}
     * @memberof TextFilter
     */
    difficulty?: Difficulty;
}
/**
 * 
 * @export
 * @interface TextSort
 */
export interface TextSort {
    /**
     * 
     * @type {string}
     * @memberof TextSort
     */
    field: string;
    /**
     * 
     * @type {boolean}
     * @memberof TextSort
     */
    ascending?: boolean;
}
/**
 * 
 * @export
 * @interface TextWithQuestions
 */
export interface TextWithQuestions {
    /**
     * 
     * @type {string}
     * @memberof TextWithQuestions
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TextWithQuestions
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TextWithQuestions
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof TextWithQuestions
     */
    difficulty: string;
    /**
     * 
     * @type {number}
     * @memberof TextWithQuestions
     */
    wordCount: number;
    /**
     * 
     * @type {Array<QuestionWithCorrectOption>}
     * @memberof TextWithQuestions
     */
    questions: Array<QuestionWithCorrectOption>;
}
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenType: string;
}
/**
 * 
 * @export
 * @interface UserAvailableTexts
 */
export interface UserAvailableTexts {
    /**
     * 
     * @type {Array<Text>}
     * @memberof UserAvailableTexts
     */
    texts: Array<Text>;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof UserAvailableTexts
     */
    totalTexts: number;
}
/**
 * 
 * @export
 * @interface UserRegistration
 */
export interface UserRegistration {
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    message: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof UserRegistration
     */
    data: UserResponse;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    createdAt: string;
}
/**
 * 
 * @export
 * @interface UserStatistics
 */
export interface UserStatistics {
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    minWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    maxWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    averageWpm: number;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    averageScore: number;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    loc: Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    type: string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes a question of a text by the given id.
         * @summary Delete Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion: async (textId: string, questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('deleteQuestion', 'textId', textId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('deleteQuestion', 'questionId', questionId)
            const localVarPath = `/admin/texts/{text_id}/questions/{question_id}`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)))
                .replace(`{${"question_id"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a text by the given id.
         * @summary Delete Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteText: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('deleteText', 'textId', textId)
            const localVarPath = `/admin/texts/{text_id}`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the statistics of the admin.
         * @summary Get Admin Statistics
         * @param {string} gameMode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminStatistics: async (gameMode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameMode' is not null or undefined
            assertParamExists('getAdminStatistics', 'gameMode', gameMode)
            const localVarPath = `/admin/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (gameMode !== undefined) {
                localVarQueryParameter['game_mode'] = gameMode;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets a question of a text by the given id.
         * @summary Get Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion: async (textId: string, questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getQuestion', 'textId', textId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getQuestion', 'questionId', questionId)
            const localVarPath = `/admin/texts/{text_id}/questions/{question_id}`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)))
                .replace(`{${"question_id"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets a question statistics of a text by the given id.
         * @summary Get Question Statistics
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionStatistics: async (textId: string, questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getQuestionStatistics', 'textId', textId)
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getQuestionStatistics', 'questionId', questionId)
            const localVarPath = `/admin/texts/{text_id}/questions/{question_id}/statistics`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)))
                .replace(`{${"question_id"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the questions of a text by the given id.
         * @summary Get Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestions: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getQuestions', 'textId', textId)
            const localVarPath = `/admin/texts/{text_id}/questions`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getText', 'textId', textId)
            const localVarPath = `/admin/texts/{text_id}`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets all texts.
         * @summary Get Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTexts: async (page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/texts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * Deletes a question of a text by the given id.
         * @summary Delete Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQuestion(textId: string, questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQuestion(textId, questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.deleteQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a text by the given id.
         * @summary Delete Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteText(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Text>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteText(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.deleteText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the statistics of the admin.
         * @summary Get Admin Statistics
         * @param {string} gameMode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdminStatistics(gameMode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminStatistics(gameMode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getAdminStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a question of a text by the given id.
         * @summary Get Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestion(textId: string, questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionWithCorrectOption>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestion(textId, questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a question statistics of a text by the given id.
         * @summary Get Question Statistics
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionStatistics(textId: string, questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionStatistics(textId, questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getQuestionStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the questions of a text by the given id.
         * @summary Get Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestions(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QuestionWithCorrectOption>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestions(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getText(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextWithQuestions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getText(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets all texts.
         * @summary Get Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTexts(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Text>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTexts(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.getTexts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * Deletes a question of a text by the given id.
         * @summary Delete Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion(textId: string, questionId: string, options?: any): AxiosPromise<Question> {
            return localVarFp.deleteQuestion(textId, questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a text by the given id.
         * @summary Delete Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteText(textId: string, options?: any): AxiosPromise<Text> {
            return localVarFp.deleteText(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the statistics of the admin.
         * @summary Get Admin Statistics
         * @param {string} gameMode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminStatistics(gameMode: string, options?: any): AxiosPromise<AdminStatistics> {
            return localVarFp.getAdminStatistics(gameMode, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets a question of a text by the given id.
         * @summary Get Question
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion(textId: string, questionId: string, options?: any): AxiosPromise<QuestionWithCorrectOption> {
            return localVarFp.getQuestion(textId, questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets a question statistics of a text by the given id.
         * @summary Get Question Statistics
         * @param {string} textId 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionStatistics(textId: string, questionId: string, options?: any): AxiosPromise<QuestionStatistics> {
            return localVarFp.getQuestionStatistics(textId, questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the questions of a text by the given id.
         * @summary Get Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestions(textId: string, options?: any): AxiosPromise<Array<QuestionWithCorrectOption>> {
            return localVarFp.getQuestions(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets a text by the given id.
         * @summary Get Text
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText(textId: string, options?: any): AxiosPromise<TextWithQuestions> {
            return localVarFp.getText(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets all texts.
         * @summary Get Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTexts(page?: number, pageSize?: number, options?: any): AxiosPromise<Array<Text>> {
            return localVarFp.getTexts(page, pageSize, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * Deletes a question of a text by the given id.
     * @summary Delete Question
     * @param {string} textId 
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public deleteQuestion(textId: string, questionId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).deleteQuestion(textId, questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a text by the given id.
     * @summary Delete Text
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public deleteText(textId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).deleteText(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the statistics of the admin.
     * @summary Get Admin Statistics
     * @param {string} gameMode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getAdminStatistics(gameMode: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getAdminStatistics(gameMode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a question of a text by the given id.
     * @summary Get Question
     * @param {string} textId 
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getQuestion(textId: string, questionId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getQuestion(textId, questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a question statistics of a text by the given id.
     * @summary Get Question Statistics
     * @param {string} textId 
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getQuestionStatistics(textId: string, questionId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getQuestionStatistics(textId, questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the questions of a text by the given id.
     * @summary Get Questions
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getQuestions(textId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getQuestions(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a text by the given id.
     * @summary Get Text
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getText(textId: string, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getText(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets all texts.
     * @summary Get Texts
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getTexts(page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).getTexts(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * User passes their refresh token to get a new access token. TODO: Invalidate refresh token on use.
         * @summary Get Token
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getToken: async (refreshToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshToken' is not null or undefined
            assertParamExists('getToken', 'refreshToken', refreshToken)
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (refreshToken !== undefined) {
                localVarQueryParameter['refresh_token'] = refreshToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * User passes their refresh token to get a new access token. TODO: Invalidate refresh token on use.
         * @summary Get Token
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getToken(refreshToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getToken(refreshToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.getToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * User passes their refresh token to get a new access token. TODO: Invalidate refresh token on use.
         * @summary Get Token
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getToken(refreshToken: string, options?: any): AxiosPromise<any> {
            return localVarFp.getToken(refreshToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * User passes their refresh token to get a new access token. TODO: Invalidate refresh token on use.
     * @summary Get Token
     * @param {string} refreshToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public getToken(refreshToken: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).getToken(refreshToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GameApi - axios parameter creator
 * @export
 */
export const GameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextQuestions: async (textId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('getNextQuestions', 'textId', textId)
            const localVarPath = `/game/texts/{text_id}/questions/next`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextText: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/game/texts/next`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnswers: async (textId: string, bodyPostAnswers: BodyPostAnswers, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textId' is not null or undefined
            assertParamExists('postAnswers', 'textId', textId)
            // verify required parameter 'bodyPostAnswers' is not null or undefined
            assertParamExists('postAnswers', 'bodyPostAnswers', bodyPostAnswers)
            const localVarPath = `/game/texts/{text_id}/answers`
                .replace(`{${"text_id"}}`, encodeURIComponent(String(textId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bodyPostAnswers, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GameApi - functional programming interface
 * @export
 */
export const GameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GameApiAxiosParamCreator(configuration)
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextQuestions(textId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Question>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextQuestions(textId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.getNextQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextText(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Text>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextText(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.getNextText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Result>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postAnswers(textId, bodyPostAnswers, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GameApi.postAnswers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GameApi - factory interface
 * @export
 */
export const GameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GameApiFp(configuration)
    return {
        /**
         * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
         * @summary Get Next Questions
         * @param {string} textId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextQuestions(textId: string, options?: any): AxiosPromise<Array<Question>> {
            return localVarFp.getNextQuestions(textId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
         * @summary Get Next Text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextText(options?: any): AxiosPromise<Text> {
            return localVarFp.getNextText(options).then((request) => request(axios, basePath));
        },
        /**
         * Accepts the question answers and other statistics. Returns the results to the answers.
         * @summary Post Answers
         * @param {string} textId 
         * @param {BodyPostAnswers} bodyPostAnswers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: any): AxiosPromise<Array<Result>> {
            return localVarFp.postAnswers(textId, bodyPostAnswers, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GameApi - object-oriented interface
 * @export
 * @class GameApi
 * @extends {BaseAPI}
 */
export class GameApi extends BaseAPI {
    /**
     * Gets next 10 questions that the user has not attempted before. NOTE: The current implementation returns 10 random questions for the given text, regardless of which questions the user has seen.
     * @summary Get Next Questions
     * @param {string} textId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public getNextQuestions(textId: string, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).getNextQuestions(textId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the next text that the user has not attempted before. NOTE: The current implementation returns a random text, regardless of which texts the user has seen.
     * @summary Get Next Text
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public getNextText(options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).getNextText(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Accepts the question answers and other statistics. Returns the results to the answers.
     * @summary Post Answers
     * @param {string} textId 
     * @param {BodyPostAnswers} bodyPostAnswers 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameApi
     */
    public postAnswers(textId: string, bodyPostAnswers: BodyPostAnswers, options?: RawAxiosRequestConfig) {
        return GameApiFp(this.configuration).postAnswers(textId, bodyPostAnswers, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistory: async (historyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'historyId' is not null or undefined
            assertParamExists('getHistory', 'historyId', historyId)
            const localVarPath = `/users/current/results/{history_id}`
                .replace(`{${"history_id"}}`, encodeURIComponent(String(historyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAvailableTexts: async (page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/available_texts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bodyGetUserAvailableTexts, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/current/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logs in a user. Returns access token and refresh token.
         * @summary Login User
         * @param {string} username 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (username: string, password: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('loginUser', 'username', username)
            // verify required parameter 'password' is not null or undefined
            assertParamExists('loginUser', 'password', password)
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }

            if (password !== undefined) {
                localVarQueryParameter['password'] = password;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Registers a new user.
         * @summary Register User
         * @param {string} username 
         * @param {string} email 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (username: string, email: string, password: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('registerUser', 'username', username)
            // verify required parameter 'email' is not null or undefined
            assertParamExists('registerUser', 'email', email)
            // verify required parameter 'password' is not null or undefined
            assertParamExists('registerUser', 'password', password)
            const localVarPath = `/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (password !== undefined) {
                localVarQueryParameter['password'] = password;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<History>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getHistories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistory(historyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<History>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistory(historyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserAvailableTexts>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserAvailableTexts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserStatistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserStatistics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Logs in a user. Returns access token and refresh token.
         * @summary Login User
         * @param {string} username 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(username: string, password: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(username, password, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Registers a new user.
         * @summary Register User
         * @param {string} username 
         * @param {string} email 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(username: string, email: string, password: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRegistration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(username, email, password, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Gets the history of games played by the user.
         * @summary Get Histories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistories(options?: any): AxiosPromise<Array<History>> {
            return localVarFp.getHistories(options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the history of games played by the user.
         * @summary Get History
         * @param {string} historyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistory(historyId: string, options?: any): AxiosPromise<History> {
            return localVarFp.getHistory(historyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
         * @summary Get User Available Texts
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: any): AxiosPromise<UserAvailableTexts> {
            return localVarFp.getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the statistics based on the user\'s game history.
         * @summary Get User Statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics(options?: any): AxiosPromise<UserStatistics> {
            return localVarFp.getUserStatistics(options).then((request) => request(axios, basePath));
        },
        /**
         * Logs in a user. Returns access token and refresh token.
         * @summary Login User
         * @param {string} username 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(username: string, password: string, options?: any): AxiosPromise<Token> {
            return localVarFp.loginUser(username, password, options).then((request) => request(axios, basePath));
        },
        /**
         * Registers a new user.
         * @summary Register User
         * @param {string} username 
         * @param {string} email 
         * @param {string} password 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(username: string, email: string, password: string, options?: any): AxiosPromise<UserRegistration> {
            return localVarFp.registerUser(username, email, password, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Gets the history of games played by the user.
     * @summary Get Histories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getHistories(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getHistories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the history of games played by the user.
     * @summary Get History
     * @param {string} historyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getHistory(historyId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getHistory(historyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the texts not read by the user. Returns the texts paginated and sorted/filtered by the given parameters.
     * @summary Get User Available Texts
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {BodyGetUserAvailableTexts} [bodyGetUserAvailableTexts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserAvailableTexts(page?: number, pageSize?: number, bodyGetUserAvailableTexts?: BodyGetUserAvailableTexts, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserAvailableTexts(page, pageSize, bodyGetUserAvailableTexts, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the statistics based on the user\'s game history.
     * @summary Get User Statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserStatistics(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserStatistics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Logs in a user. Returns access token and refresh token.
     * @summary Login User
     * @param {string} username 
     * @param {string} password 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public loginUser(username: string, password: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).loginUser(username, password, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Registers a new user.
     * @summary Register User
     * @param {string} username 
     * @param {string} email 
     * @param {string} password 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public registerUser(username: string, email: string, password: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).registerUser(username, email, password, options).then((request) => request(this.axios, this.basePath));
    }
}



